test = {
  "artifacts": [],
  "blocker": None,
  "ciTestId": None,
  "configXML": None,
  "dependsOnMethods": None,
  "finishTime": None,
  "id": None,
  "knownIssue": None,
  "message": None,
  "messageHashCode": None,
  "name": "NAME",
  "needRerun": None,
  "retry": None,
  "startTime": None,
  "status": None,
  "testArgs": None,
  "testCaseId": "TEST_CASE_ID_INT",
  "testClass": None,
  "testGroup": None,
  "testMetrics": None,
  "testRunId": "TEST_RUN_ID_INT",
  "workItems": []
}
